ShfMgmtEg.Mvc/Controllers/AuthController.cs
using System.Net;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using RestSharp;
using ShfMgmtEg.Core.Dtos.User;
using ShfMgmtEg.Mvc.Models;
using ShfMgmtEg.Mvc.Services;


namespace ShfMgmtEg.Mvc.Controllers;


public class AuthController : Controller
{
    private IHttpContextAccessor _httpContextAccessor;
    private readonly RequestService _requestService;

    public AuthController(IHttpContextAccessor httpContextAccessor, RequestService requestService)
    {
        _httpContextAccessor = httpContextAccessor;
        _requestService = requestService;
    }
    // GET
    
    public IActionResult Login()
    {
        var model = new LoginModel();
        
        return View(model);
    }
    
    [HttpPost]
    public async Task<IActionResult> Login(LoginUser user)
    {
        var response = await _requestService.Post<RestResponse>("Auth/Login", user);
        
        if (response.statusCode == HttpStatusCode.OK)
        {
            string token = response.data.ToString();
            var model = new LoginModel
            {
                UserName = user.UserName,
                Password = user.Password,
                Data = token
            };
            _httpContextAccessor.HttpContext?.Session.SetString("AccessToken", token);

            _ = HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(new ClaimsIdentity(new List<Claim>
            {
                new Claim(ClaimTypes.Name, user.UserName),
                new Claim(ClaimTypes.Role, "User")
            }, CookieAuthenticationDefaults.AuthenticationScheme)), new AuthenticationProperties
            {
                IsPersistent = true,
                ExpiresUtc = DateTime.UtcNow.AddMinutes(20)
            });
            return RedirectToAction("Index", "Home", model);
        }
        else
        {

            string message = string.IsNullOrEmpty(response.errors) 
                ? response.message : response.errors?.password || response.errors?.username;
            var model = new LoginModel
            {
                UserName = user.UserName,
                Password = user.Password,
                ErrorMessage = message
            };
            return View(model);
        }

    }
    
    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        return RedirectToAction("Login");
    }
    
    public IActionResult Register()
    {
        var model = new RegisterModel();
        
        return View(model);
    }
    
    [HttpPost]
    public async Task<IActionResult> Register(RegisterUser user)
    {
        var response = await _requestService.Post<RestResponse>("Auth/Register", user);

       
            if ( response?.isSuccess != null && response?.isSuccess == true)
            {
                var model = new RegisterModel
                {
                    UserName = user.UserName,
                    Password = user.Password,
                    Data = response?.data?.ToString()
                };
                return RedirectToAction("Login", model);
            }
            else
            {
                string message = response?.message;
                   
                var model = new RegisterModel
                {
                    UserName = user.UserName,
                    Password = user.Password,
                    ErrorMessage = message
                };
                return View(model);
            }
    }
}

ShfMgmtEg.Mvc/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ShfMgmtEg.Mvc.Controllers;

[Authorize]
public class RolesController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
}

ShfMgmtEg.Mvc/Controllers/ShiftsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RestSharp;

namespace ShfMgmtEg.Mvc.Controllers;

[Authorize]
public class ShiftsController : Controller
{
    
    // GET
    public async Task<IActionResult> Index()
    {
        var options = new RestClientOptions("https://localhost:7261")
        {
            MaxTimeout = -1,
        };
        var client = new RestClient(options);
        var request = new RestRequest("/api/Shift/5", Method.Get);
        request.AddHeader("Content-Type", "application/json");
        request.AddHeader("Authorization", "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbW9iaWxlcGhvbmUiOiIxMjM0NTY3ODkwIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzExOTI1OTM5LCJleHAiOjE3MTIwMTIzMzksImlhdCI6MTcxMTkyNTkzOX0.9XHJGDe0tQjQ1syMKbccjn6ygdWaJs6OU8ADaq6ZJbW2yZhuwFaooEvNEwOFCmjzjRp0auj-2o-q33KvcZG_Sg");
        var body = @"";
        request.AddStringBody(body, DataFormat.Json);
        RestResponse response = await client.ExecuteAsync(request);
        Console.WriteLine(response.Content);
        return View(response);
    }
}

ShfMgmtEg.Mvc/Controllers/TeamsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RestSharp;
using ShfMgmtEg.Core.Dtos.Team;
using ShfMgmtEg.Core.Response;
using ShfMgmtEg.Mvc.Services;

namespace ShfMgmtEg.Mvc.Controllers;

[Authorize]
public class TeamsController : Controller
{
    private readonly IConfiguration _configuration;
    private readonly IHttpContextAccessor _httpContextAccessor;
    private readonly RequestService _requestService;

    public TeamsController(IConfiguration configuration, IHttpContextAccessor httpContextAccessor, RequestService requestService)
    {
        _configuration = configuration;
        _httpContextAccessor = httpContextAccessor;
        _requestService = requestService;
    }
    // GET
    public async Task<IActionResult> Index()
    {
        var response = await _requestService.Get<RestResponse>("Team");
        if ( response?.isSuccess != null && response?.isSuccess == true)
        {
            List<GetTeam> model = response?.data?.ToObject<List<GetTeam>>() ?? "VALUE";
          
            return View(model);
        }
        else
        {
            string? message = response?.message;

            var model = new ServiceResponse<string>();
            model.Message = message;
            model.Data = null;
            return View(model);
        }
        
    }
}

ShfMgmtEg.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - ShfMgmtEg.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/ShfMgmtEg.Mvc.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <link href="~/lib/kendo/styles/default-main.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/kendo/js/kendo.all.min.js"></script>
  
    <script src="~/lib/kendo-ui-license.js"></script>

</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShfMgmtEg.Mvc</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            @if (User.Identity.IsAuthenticated)
            {
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Personeller</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="Index">Takımlar</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shifts" asp-action="Index">Vardiyalar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roller</a>
                        </li>
                    </ul>
                </div>
            }

        </div>
        @if (User.Identity.IsAuthenticated)
        {
            <div class="container-fluid justify-content-end">
                <a class="navbar-brand" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

            </div>
        }
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - ShfMgmtEg.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>